version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"

    schedule:
      interval: "daily"
      time: "22:30"
      timezone: "America/New_York"

    open-pull-requests-limit: 5
    target-branch:  "master"
    labels:
      - "npm"
      - "dependencies"
      - "security"
    reviewers:
      - "darknautic"
    assignees:
      - "darknautic"
    insecure-external-code-execution: deny


  # Maintain dependencies for javascript
  - package-ecosystem: "javascript"
    directory: "/"

    schedule:
      interval: "daily"
      time: "22:30"
      timezone: "America/New_York"

    open-pull-requests-limit: 5
    target-branch:  "master"
    labels:
      - "javascript"
      - "dependencies"
      - "security"
    reviewers:
      - "darknautic"
    assignees:
      - "darknautic"
    insecure-external-code-execution: deny

